# Generated by Django 5.2.6 on 2025-10-06 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0003_profile_place_profile_ration_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, help_text='Available quantity in stock'),
        ),
    ]
