# Generated by Django 5.2.6 on 2025-10-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0004_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='family_members',
            field=models.IntegerField(blank=True, help_text='Total family members', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ration_card_back',
            field=models.ImageField(blank=True, null=True, upload_to='ration_cards/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ration_card_front',
            field=models.ImageField(blank=True, null=True, upload_to='ration_cards/'),
        ),
    ]
