# Generated by Django 5.2.6 on 2025-10-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0011_notification_link_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_option',
            field=models.CharField(choices=[('home', 'Home delivery'), ('pickup', 'Come and get')], default='home', max_length=16),
        ),
    ]
